name: podeo_ui_clone
description: A Podeo UI clone app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_icons: ^2.0.2
  carousel_slider: ^4.0.0
  device_preview: ^1.0.0
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/